//
//  ReelsData.swift
//  Isometrik_Video_Feeds
//
//  Created by 3embed on 25/12/24.
//

import Foundation
// Sample JSON data as a string
let jsonString = """
{
  "message": "Posts fetched successfully",
  "totalPosts": 12,
  "data": [
    {
      "_id": "652d3217721c949566f3a66f",
      "postViewsCount": 64,
      "title": "#testt",
      "imageUrl1": "http://scontent-msp1-1.cdninstagram.com/o1/v/t16/f2/m86/AQNkARaTdWVCR4tHuT1G-OSc0QQp3-RLk8cSBsZetuoSmt5fRCM5mZijYWw7Zyub45u5wqROzJGunf_IiDj-LxMrCoHa2cK7e9RBan0.mp4?stp=dst-mp4&efg=eyJxZV9ncm91cHMiOiJbXCJpZ193ZWJfZGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uY2xpcHMuYzIuNDgwLmJhc2VsaW5lIn0&_nc_cat=108&vs=8733042210141279_185011744&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9CNTRGMzZDNEExRDE0QzBDNDVEQjM1NDkxQUVEOUJBMl92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dITXlGeHptQ0VYVVpQY0RBSnQwNFVpMlN4STdicV9FQUFBRhUCAsgBACgAGAAbABUAACb28%2FCHsI3mPxUCKAJDMywXQF7XbItDlYEYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HAA%3D%3D&_nc_rid=cb6a3206d9&ccb=9-4&oh=00_AYDItMmHdjrEDtz435w-1-fj3DzSgPXiUxD7T1cemTV5sw&oe=6793E2FF&_nc_sid=10d13b%27",
      "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/t_media_lib_thumb/v1697460757/kozzii/posts/nyxq6o2qxaaxchhtn58s.jpg",
      "mediaType1": 1,
      "userId": "65293e590ea7500199eac6a2",
      "createdOn": "2023-10-16T12:52:39.111",
      "timeStamp": 1697460759111,
      "distinctViews": 70,
      "totalViews": [],
      "imageUrl1Width": "1280",
      "imageUrl1Height": "720",
      "likesCount": 8,
      "postStatus": 1,
      "shareCount": 1,
      "commentCount": 3,
      "cloudinary_public_id": "kozzii/posts/nyxq6o2qxaaxchhtn58s",
      "userName": "harshareddy31",
      "firstName": "harsha",
      "lastName": "vardhan",
      "fullName": "harshavardhan",
      "fullNameWithSpace": "harsha vardhan",
      "profilepic": "",
      "profileCoverImage": "https://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1687417712/kozzii/cover_image/kozzii_xbjqr9.png",
      "musicId": "652d3217721c946243f3a670",
      "musicData": {
        "_id": "652d3217721c946243f3a670",
        "artist": "harshareddy31",
        "audioStatus": 1,
        "audioStatusText": "active",
        "createdOn": 1697460759109,
        "duration": 10,
        "imageUrl": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1697460757/kozzii/posts/nyxq6o2qxaaxchhtn58s.jpg",
        "name": "Original by harshareddy31",
        "path": "http://res.cloudinary.com/dozbw4cww/video/upload/v1697460757/kozzii/posts/nyxq6o2qxaaxchhtn58s.aac",
        "sequenceId": 100,
        "songBackground": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1697460757/kozzii/posts/nyxq6o2qxaaxchhtn58s.jpg",
        "isOriginalSound": true
      },
      "location": {
        "longitude": 0,
        "latitude": 0
      },
      "cityForPost": "Shahmīrpet",
      "countryForPost": "IN",
      "latForPost": 17.4284406,
      "longForPost": 78.5840116,
      "isPrivate": 0,
      "isPaid": false,
      "postAmount": 0,
      "subscriptionAmount": 0,
      "TipsAmount": 12,
      "hashTags": [
        "#testt"
      ],
      "followStatus": 0,
      "postId": "652d3217721c949566f3a66f",
      "liked": false,
      "isPurchased": true,
      "isKYCApproved": false,
      "isBookMarked": false
    },
    {
      "_id": "651664d2eb3d2f594da7861e",
      "postViewsCount": 65,
      "title": "",
      "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1695964997/dubly/posts/hrtcv37qtoasqoigiviq.jpg",
      "thumbnailUrl1": "http://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1695966417/KOZII/posts/1695966409544.jpg",
      "mediaType1": 0,
      "userId": "651661cbeb3d2f8faca7860e",
      "createdOn": "2023-09-29T05:46:58.566",
      "timeStamp": 1695966418566,
      "distinctViews": 74,
      "totalViews": [],
      "imageUrl1Width": "640",
      "imageUrl1Height": "1096",
      "likesCount": 11,
      "mentionedUsers": [],
      "postStatus": 1,
      "shareCount": 0,
      "commentCount": 3,
      "cloudinary_public_id": "kozzii/posts/nyxq6o2qxaaxchhtn58s",
      "userName": "manisha",
      "firstName": "Navpreet Kaur",
      "lastName": "M",
      "fullName": "ManishaM",
      "fullNameWithSpace": "Manisha M",
      "profilepic": "",
      "profileCoverImage": "",
      "categoryId": "",
      "categoryName": "",
      "categoryUrl": "",
      "musicId": "651664d2eb3d2f622ba7861f",
      "musicData": {},
      "location": {
        "longitude": 0,
        "latitude": 0
      },
      "isPrivate": 0,
      "isPaid": false,
      "postAmount": 0,
      "subscriptionAmount": 0,
      "TipsAmount": 0,
      "hashTags": [],
      "followStatus": 1,
      "postId": "651664d2eb3d2f594da7861e",
      "liked": false,
      "isPurchased": true,
      "isKYCApproved": false,
      "isBookMarked": false
    },
    {
      "_id": "651cfa7e55793100bcccb6ce",
      "postViewsCount": 65,
      "title": "#priya",
      "imageUrl1": "http://res.cloudinary.com/dx0qtfwvm/video/upload/v1696397855/KOZII/posts/1696397828571.mp4",
      "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/t_media_lib_thumb/v1696397948/dubly/posts/woih5tism7mf3uufhsxt.jpg",
      "mediaType1": 1,
      "userId": "651cebb055793143c7ccb6af",
      "createdOn": "2023-10-04T05:39:10.117",
      "timeStamp": 1696397950117,
      "distinctViews": 75,
      "totalViews": [],
      "imageUrl1Width": "1072",
      "imageUrl1Height": "2128",
      "likesCount": 9,
      "mentionedUsers": [],
      "postStatus": 1,
      "shareCount": 1,
      "commentCount": 4,
      "cloudinary_public_id": "dubly/posts/woih5tism7mf3uufhsxt",
      "userName": "priyah",
      "firstName": "Priya",
      "lastName": "H",
      "fullName": "PriyaH",
      "fullNameWithSpace": "Priya H",
      "profilepic": "",
      "profileCoverImage": "",
      "categoryId": "",
      "categoryName": "",
      "categoryUrl": "",
      "musicId": "651cf9665579317badccb6cb",
      "musicData": {
        "_id": "651cf9665579317badccb6cb",
        "artist": "priyah",
        "audioStatus": 1,
        "audioStatusText": "active",
        "createdOn": 1696397670666,
        "duration": 10,
        "imageUrl": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.jpg",
        "name": "Original by priyah",
        "path": "http://res.cloudinary.com/dozbw4cww/video/upload/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.aac",
        "sequenceId": 100,
        "songBackground": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.jpg",
        "isOriginalSound": true
      },
      "location": {
        "longitude": 0,
        "latitude": 0
      },
      "cityForPost": "",
      "countryForPost": "",
      "latForPost": 0,
      "longForPost": 0,
      "isPrivate": 0,
      "isPaid": false,
      "postAmount": 0,
      "subscriptionAmount": 0,
      "TipsAmount": 0,
      "hashTags": [
        "#priya"
      ],
      "followStatus": 1,
      "postId": "651cfa7e55793100bcccb6ce",
      "liked": false,
      "isPurchased": true,
      "isKYCApproved": false,
      "isBookMarked": false
    },
       {
        "_id": "651cfa22557931d818ccb6cd",
        "postViewsCount": 63,
        "title": "",
        "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1697029952/dubly/posts/imzmh8xw2phzbomlkywg.jpg",
        "thumbnailUrl1": "http://res.cloudinary.com/dx0qtfwvm/video/upload/t_media_lib_thumb/v1696397855/KOZII/posts/1696397828571.jpg",
        "mediaType1": 0,
        "userId": "651cf3245579316379ccb6c0",
        "createdOn": "2023-10-04T05:37:38.720",
        "timeStamp": 1696397858720,
        "distinctViews": 68,
        "totalViews": [],
        "imageUrl1Width": "1080",
        "imageUrl1Height": "1920",
        "likesCount": 5,
        "mentionedUsers": [],
        "postStatus": 1,
        "shareCount": 0,
        "commentCount": 3,
        "cloudinary_public_id": "",
        "userName": "piyah",
        "firstName": "Piya",
        "lastName": "H",
        "fullName": "PiyaH",
        "fullNameWithSpace": "Piya H",
        "profilepic": "",
        "profileCoverImage": "",
        "categoryId": "",
        "categoryName": "",
        "categoryUrl": "",
        "musicId": "651cf9665579317badccb6cb",
        "musicData": {
          "_id": "651cf9665579317badccb6cb",
          "artist": "priyah",
          "audioStatus": 1,
          "audioStatusText": "active",
          "createdOn": 1696397670666,
          "duration": 10,
          "imageUrl": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.jpg",
          "name": "Original by priyah",
          "path": "http://res.cloudinary.com/dozbw4cww/video/upload/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.aac",
          "sequenceId": 100,
          "songBackground": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.jpg",
          "isOriginalSound": true
        },
        "location": {
          "longitude": 0,
          "latitude": 0
        },
        "place": "",
        "countrySname": "",
        "city": "",
        "placeId": "",
        "orientation": 0,
        "isStar": true,
        "trending_score": 0,
        "allowDownload": true,
        "allowComment": true,
        "allowDuet": true,
        "productIds": [],
        "productData": [],
        "cityForPost": "",
        "countryForPost": "",
        "latForPost": 0,
        "longForPost": 0,
        "locationForPost": {
          "lat": 0,
          "lon": 0
        },
        "isPrivate": 0,
        "isPaid": false,
        "postAmount": 0,
        "subscriptionAmount": 100,
        "TipsAmount": 0,
        "hashTags": [],
        "followStatus": 1,
        "postId": "651cfa22557931d818ccb6cd",
        "liked": false,
        "isPurchased": true,
        "isKYCApproved": false,
        "isBookMarked": false
      },
       {
          "_id": "6515683feb3d2f80dca785e2",
          "postViewsCount": 76,
          "title": "@priyah ",
          "imageUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.mp4",
          "thumbnailUrl1": "http://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1695901758/KOZII/posts/1695901754282.jpg",
          "mediaType1": 1,
          "userId": "651566a2eb3d2f0c29a785dd",
          "createdOn": "2023-09-28T11:49:19.437",
          "timeStamp": 1695901759437,
          "distinctViews": 89,
          "totalViews": [],
          "imageUrl1Width": "828",
          "imageUrl1Height": "1696",
          "likesCount": 15,
          "mentionedUsers": [
            [],
            []
          ],
          "postStatus": 1,
          "shareCount": 1,
          "commentCount": 4,
          "cloudinary_public_id": "",
          "userName": "ammuh",
          "firstName": "Ammu",
          "lastName": "H",
          "fullName": "AmmuH",
          "fullNameWithSpace": "Ammu H",
          "profilepic": "http://res.cloudinary.com/dx0qtfwvm/image/upload/v1695909052/KOZII/profile_images/651566a2eb3d2f0c29a785dd.jpg",
          "profileCoverImage": "http://res.cloudinary.com/dx0qtfwvm/image/upload/q_60/v1695909020/KOZII/cover_images/651566a2eb3d2f0c29a785dd.jpg",
          "categoryId": "",
          "categoryName": "",
          "categoryUrl": "",
          "musicId": "6515683feb3d2f6dc9a785e5",
          "musicData": {},
          "location": {
            "longitude": 0,
            "latitude": 0
          },
          "place": "",
          "countrySname": "",
          "city": "",
          "placeId": "",
          "orientation": 0,
          "isStar": true,
          "trending_score": 0,
          "allowDownload": true,
          "allowComment": true,
          "allowDuet": true,
          "productIds": [],
          "productData": [],
          "cityForPost": "",
          "countryForPost": "",
          "latForPost": 0,
          "longForPost": 0,
          "locationForPost": {
            "lat": 0,
            "lon": 0
          },
          "isPrivate": 0,
          "isPaid": false,
          "postAmount": 0,
          "subscriptionAmount": 100,
          "TipsAmount": 0,
          "hashTags": [],
          "followStatus": 0,
          "postId": "6515683feb3d2f80dca785e2",
          "liked": false,
          "isPurchased": true,
          "isKYCApproved": false,
          "isBookMarked": false
        },
       {
              "_id": "65165f46eb3d2f2e2fa78603",
              "postViewsCount": 78,
              "title": "#car",
              "imageUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/v1696397669/dubly/posts/lvcgptmb5rr7yskicywo.mp4",
              "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/t_media_lib_thumb/v1695964997/dubly/posts/hrtcv37qtoasqoigiviq.jpg",
              "mediaType1": 1,
              "userId": "64e73cb9701ab139eb59ad2b",
              "createdOn": "2023-09-29T05:23:18.348",
              "timeStamp": 1695964998348,
              "distinctViews": 87,
              "totalViews": [],
              "imageUrl1Width": "1080",
              "imageUrl1Height": "2223",
              "likesCount": 13,
              "mentionedUsers": [],
              "postStatus": 1,
              "shareCount": 0,
              "commentCount": 2,
              "cloudinary_public_id": "dubly/posts/hrtcv37qtoasqoigiviq",
              "userName": "jeetu04",
              "firstName": "Jeetu",
              "lastName": "",
              "fullName": "Jeetu",
              "fullNameWithSpace": "Jeetu ",
              "profilepic": "",
              "profileCoverImage": "https://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1687417712/kozzii/cover_image/kozzii_xbjqr9.png",
              "categoryId": "",
              "categoryName": "",
              "categoryUrl": "",
              "musicId": "65165f46eb3d2f6130a78604",
              "musicData": {},
              "location": {
                "longitude": 77.5895754,
                "latitude": 13.0287221
              },
              "place": "3Embed Software Technologies Pvt. Ltd.",
              "countrySname": "IN",
              "city": "Bengaluru",
              "placeId": "ChIJLXG3TrkXrjsR3QxwQanjPkA",
              "orientation": 0,
              "isStar": false,
              "trending_score": 0,
              "allowDownload": true,
              "allowComment": true,
              "allowDuet": true,
              "productIds": [],
              "productData": [],
              "cityForPost": "Bengaluru",
              "countryForPost": "IN",
              "latForPost": 0,
              "longForPost": 0,
              "locationForPost": {
                "lat": 0,
                "lon": 0
              },
              "isPrivate": 0,
              "isPaid": false,
              "postAmount": 0,
              "subscriptionAmount": 0,
              "TipsAmount": 1,
              "hashTags": [
                "#car"
              ],
              "followStatus": 0,
              "postId": "65165f46eb3d2f2e2fa78603",
              "liked": false,
              "isPurchased": true,
              "isKYCApproved": false,
              "isBookMarked": false
            }
  ]
}
"""

//       {
//                "_id": "65165f46eb3d2f2e2fa78603",
//                "postViewsCount": 78,
//                "title": "#car",
//                "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1695964997/dubly/posts/hrtcv37qtoasqoigiviq.jpg",
//                "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/t_media_lib_thumb/v1695964997/dubly/posts/hrtcv37qtoasqoigiviq.jpg",
//                "mediaType1": 0,
//                "userId": "64e73cb9701ab139eb59ad2b",
//                "createdOn": "2023-09-29T05:23:18.348",
//                "timeStamp": 1695964998348,
//                "distinctViews": 87,
//                "totalViews": [],
//                "imageUrl1Width": "1080",
//                "imageUrl1Height": "2223",
//                "likesCount": 13,
//                "mentionedUsers": [],
//                "postStatus": 1,
//                "shareCount": 0,
//                "commentCount": 2,
//                "cloudinary_public_id": "dubly/posts/hrtcv37qtoasqoigiviq",
//                "userName": "jeetu04",
//                "firstName": "Jeetu",
//                "lastName": "",
//                "fullName": "Jeetu",
//                "fullNameWithSpace": "Jeetu ",
//                "profilepic": "",
//                "profileCoverImage": "https://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1687417712/kozzii/cover_image/kozzii_xbjqr9.png",
//                "categoryId": "",
//                "categoryName": "",
//                "categoryUrl": "",
//                "musicId": "65165f46eb3d2f6130a78604",
//                "musicData": {},
//                "location": {
//                  "longitude": 77.5895754,
//                  "latitude": 13.0287221
//                },
//                "place": "3Embed Software Technologies Pvt. Ltd.",
//                "countrySname": "IN",
//                "city": "Bengaluru",
//                "placeId": "ChIJLXG3TrkXrjsR3QxwQanjPkA",
//                "orientation": 0,
//                "isStar": false,
//                "trending_score": 0,
//                "allowDownload": true,
//                "allowComment": true,
//                "allowDuet": true,
//                "productIds": [],
//                "productData": [],
//                "cityForPost": "Bengaluru",
//                "countryForPost": "IN",
//                "latForPost": 0,
//                "longForPost": 0,
//                "locationForPost": {
//                  "lat": 0,
//                  "lon": 0
//                },
//                "isPrivate": 0,
//                "isPaid": false,
//                "postAmount": 0,
//                "subscriptionAmount": 0,
//                "TipsAmount": 1,
//                "hashTags": [
//                  "#car"
//                ],
//                "followStatus": 0,
//                "postId": "65165f46eb3d2f2e2fa78603",
//                "liked": false,
//                "isPurchased": true,
//                "isKYCApproved": false,
//                "isBookMarked": false
//              }, {
//                  "_id": "65269f415dee0e4cb584c197",
//                  "postViewsCount": 75,
//                  "title": "#dhoni\n#msd",
//                  "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1697029952/dubly/posts/imzmh8xw2phzbomlkywg.jpg",
//                  "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/t_media_lib_thumb/v1697029952/dubly/posts/imzmh8xw2phzbomlkywg.jpg",
//                  "mediaType1": 0,
//                  "userId": "64e73cb9701ab139eb59ad2b",
//                  "createdOn": "2023-10-11T13:12:33.361",
//                  "timeStamp": 1697029953361,
//                  "distinctViews": 80,
//                  "totalViews": [],
//                  "imageUrl1Width": "1080",
//                  "imageUrl1Height": "863",
//                  "likesCount": 17,
//                  "mentionedUsers": [],
//                  "postStatus": 1,
//                  "shareCount": 0,
//                  "commentCount": 4,
//                  "cloudinary_public_id": "dubly/posts/imzmh8xw2phzbomlkywg",
//                  "userName": "jeetu04",
//                  "firstName": "Jeetu",
//                  "lastName": "",
//                  "fullName": "Jeetu",
//                  "fullNameWithSpace": "Jeetu ",
//                  "profilepic": "",
//                  "profileCoverImage": "https://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1687417712/kozzii/cover_image/kozzii_xbjqr9.png",
//                  "categoryId": "64e5da0db6d964001476b7e3",
//                  "categoryName": "Lifehacks",
//                  "categoryUrl": "http://res.cloudinary.com/dx0qtfwvm/image/upload/v1692785164/uyxavtnvf8rcknvypcmw.png",
//                  "musicId": "65269f415dee0eda8d84c198",
//                  "musicData": {},
//                  "location": {
//                    "longitude": 77.5895845,
//                    "latitude": 13.0287034
//                  },
//                  "place": "3Embed Software Technologies Pvt. Ltd.",
//                  "countrySname": "IN",
//                  "city": "Bengaluru",
//                  "placeId": "ChIJLXG3TrkXrjsR3QxwQanjPkA",
//                  "orientation": 0,
//                  "isStar": false,
//                  "trending_score": 0,
//                  "allowDownload": true,
//                  "allowComment": true,
//                  "allowDuet": true,
//                  "productIds": [],
//                  "productData": [],
//                  "cityForPost": "Bengaluru",
//                  "countryForPost": "IN",
//                  "latForPost": 13.0286559,
//                  "longForPost": 77.5894823,
//                  "locationForPost": {
//                    "lat": 13.0286559,
//                    "lon": 77.5894823
//                  },
//                  "isPrivate": 0,
//                  "isPaid": false,
//                  "postAmount": 0,
//                  "subscriptionAmount": 0,
//                  "TipsAmount": 0,
//                  "hashTags": [
//                    "#dhoni",
//                    "#msd"
//                  ],
//                  "followStatus": 0,
//                  "postId": "65269f415dee0e4cb584c197",
//                  "liked": false,
//                  "isPurchased": true,
//                  "isKYCApproved": false,
//                  "isBookMarked": false
//                }, {
//                    "_id": "6529611507359d18a0beb648",
//                    "postViewsCount": 56,
//                    "title": "ENJOYING ME TIME!!!!",
//                    "imageUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.mp4",
//                    "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/video/upload/t_media_lib_thumb/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.jpg",
//                    "mediaType1": 1,
//                    "userId": "6516c0e7eb3d2f5b75a78693",
//                    "createdOn": "2023-10-13T15:24:05.865",
//                    "timeStamp": 1697210645865,
//                    "distinctViews": 64,
//                    "totalViews": [],
//                    "imageUrl1Width": "1072",
//                    "imageUrl1Height": "2352",
//                    "likesCount": 12,
//                    "mentionedUsers": [],
//                    "postStatus": 1,
//                    "shareCount": 0,
//                    "commentCount": 1,
//                    "cloudinary_public_id": "kozzii/posts/quvief8mgpdxroaumy7r",
//                    "userName": "shakis",
//                    "firstName": "Brenda",
//                    "lastName": "ELUNG",
//                    "fullName": "BrendaELUNG",
//                    "fullNameWithSpace": "Brenda ELUNG",
//                    "profilepic": "http://res.cloudinary.com/dozbw4cww/image/upload/v1713573060/kozzii/profile_image/6516c0e7eb3d2f5b75a78693.jpg",
//                    "profileCoverImage": "",
//                    "categoryId": "6111fb0820ec2262b808e4b1",
//                    "categoryName": "Entertainment",
//                    "categoryUrl": "http://res.cloudinary.com/db3lvxbct/image/upload/v1628568327/nukwvlzi75i5yovu3agq.png",
//                    "musicId": "6529611507359d864ebeb649",
//                    "musicData": {
//                      "_id": "6529611507359d864ebeb649",
//                      "artist": "shakis",
//                      "audioStatus": 1,
//                      "audioStatusText": "active",
//                      "createdOn": 1697210645861,
//                      "duration": 10,
//                      "imageUrl": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.jpg",
//                      "name": "Original by shakis",
//                      "path": "http://res.cloudinary.com/dozbw4cww/video/upload/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.aac",
//                      "sequenceId": 100,
//                      "songBackground": "http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1697210643/kozzii/posts/quvief8mgpdxroaumy7r.jpg",
//                      "isOriginalSound": true
//                    },
//                    "location": {
//                      "longitude": 0,
//                      "latitude": 0
//                    },
//                    "place": "",
//                    "countrySname": "",
//                    "city": "",
//                    "placeId": "",
//                    "orientation": 0,
//                    "isStar": true,
//                    "trending_score": 0,
//                    "allowDownload": true,
//                    "allowComment": true,
//                    "allowDuet": true,
//                    "productIds": [],
//                    "productData": [],
//                    "cityForPost": "Dibombari",
//                    "countryForPost": "CM",
//                    "latForPost": 4.0146495,
//                    "longForPost": 9.1280338,
//                    "locationForPost": {
//                      "lat": 4.0146495,
//                      "lon": 9.1280338
//                    },
//                    "isPrivate": 0,
//                    "isPaid": false,
//                    "postAmount": 0,
//                    "subscriptionAmount": 50,
//                    "TipsAmount": 0,
//                    "hashTags": [],
//                    "followStatus": 1,
//                    "postId": "6529611507359d18a0beb648",
//                    "liked": false,
//                    "isPurchased": true,
//                    "isKYCApproved": false,
//                    "isBookMarked": false
//                  }, {
//                      "_id": "651664d2eb3d2f594da7861e",
//                      "postViewsCount": 65,
//                      "title": "",
//                      "imageUrl1": "http://res.cloudinary.com/dx0qtfwvm/image/upload/v1695966417/KOZII/posts/1695966409544.jpg",
//                      "thumbnailUrl1": "http://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1695966417/KOZII/posts/1695966409544.jpg",
//                      "mediaType1": 0,
//                      "userId": "651661cbeb3d2f8faca7860e",
//                      "createdOn": "2023-09-29T05:46:58.566",
//                      "timeStamp": 1695966418566,
//                      "distinctViews": 74,
//                      "totalViews": [],
//                      "imageUrl1Width": "640",
//                      "imageUrl1Height": "1096",
//                      "likesCount": 11,
//                      "mentionedUsers": [],
//                      "postStatus": 1,
//                      "shareCount": 0,
//                      "commentCount": 3,
//                      "cloudinary_public_id": "",
//                      "userName": "manisha",
//                      "firstName": "Manisha",
//                      "lastName": "M",
//                      "fullName": "ManishaM",
//                      "fullNameWithSpace": "Manisha M",
//                      "profilepic": "",
//                      "profileCoverImage": "",
//                      "categoryId": "",
//                      "categoryName": "",
//                      "categoryUrl": "",
//                      "musicId": "651664d2eb3d2f622ba7861f",
//                      "musicData": {},
//                      "location": {
//                        "longitude": 0,
//                        "latitude": 0
//                      },
//                      "place": "",
//                      "countrySname": "",
//                      "city": "",
//                      "placeId": "",
//                      "orientation": 0,
//                      "isStar": false,
//                      "trending_score": 0,
//                      "allowDownload": true,
//                      "allowComment": true,
//                      "allowDuet": true,
//                      "productIds": [],
//                      "productData": [],
//                      "cityForPost": "",
//                      "countryForPost": "",
//                      "latForPost": 0,
//                      "longForPost": 0,
//                      "locationForPost": {
//                        "lat": 0,
//                        "lon": 0
//                      },
//                      "isPrivate": 0,
//                      "isPaid": false,
//                      "postAmount": 0,
//                      "subscriptionAmount": 0,
//                      "TipsAmount": 0,
//                      "hashTags": [],
//                      "followStatus": 1,
//                      "postId": "651664d2eb3d2f594da7861e",
//                      "liked": false,
//                      "isPurchased": true,
//                      "isKYCApproved": false,
//                      "isBookMarked": false
//                    }, {
//                        "_id": "652af813dcaccf7b302a6268",
//                        "postViewsCount": 62,
//                        "title": "Spicy coffee mix!",
//                        "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1697314834/kozzii/posts/bqvvvygjs567dbawy7hf.jpg",
//                        "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/t_media_lib_thumb/v1697314834/kozzii/posts/bqvvvygjs567dbawy7hf.jpg",
//                        "mediaType1": 0,
//                        "userId": "6516c0e7eb3d2f5b75a78693",
//                        "createdOn": "2023-10-14T20:20:35.572",
//                        "timeStamp": 1697314835572,
//                        "distinctViews": 69,
//                        "totalViews": [],
//                        "imageUrl1Width": "1080",
//                        "imageUrl1Height": "2352",
//                        "likesCount": 6,
//                        "mentionedUsers": [],
//                        "postStatus": 1,
//                        "shareCount": 0,
//                        "commentCount": 2,
//                        "cloudinary_public_id": "kozzii/posts/bqvvvygjs567dbawy7hf",
//                        "userName": "shakis",
//                        "firstName": "Brenda",
//                        "lastName": "ELUNG",
//                        "fullName": "BrendaELUNG",
//                        "fullNameWithSpace": "Brenda ELUNG",
//                        "profilepic": "http://res.cloudinary.com/dozbw4cww/image/upload/v1713573060/kozzii/profile_image/6516c0e7eb3d2f5b75a78693.jpg",
//                        "profileCoverImage": "",
//                        "categoryId": "6111fb8220ec2262b808e4b4",
//                        "categoryName": "Cooking & recipes",
//                        "categoryUrl": "http://res.cloudinary.com/db3lvxbct/image/upload/v1628568450/kb8akp8ajyj2gwu4zwvd.png",
//                        "musicId": "652af813dcaccf50282a6269",
//                        "musicData": {},
//                        "location": {
//                          "longitude": 0,
//                          "latitude": 0
//                        },
//                        "place": "",
//                        "countrySname": "",
//                        "city": "",
//                        "placeId": "",
//                        "orientation": 0,
//                        "isStar": true,
//                        "trending_score": 0,
//                        "allowDownload": true,
//                        "allowComment": true,
//                        "allowDuet": true,
//                        "productIds": [],
//                        "productData": [],
//                        "cityForPost": "Douala",
//                        "countryForPost": "CM",
//                        "latForPost": 4.0136592,
//                        "longForPost": 9.2205225,
//                        "locationForPost": {
//                          "lat": 4.0136592,
//                          "lon": 9.2205225
//                        },
//                        "isPrivate": 0,
//                        "isPaid": false,
//                        "postAmount": 0,
//                        "subscriptionAmount": 50,
//                        "TipsAmount": 0,
//                        "hashTags": [],
//                        "followStatus": 1,
//                        "postId": "652af813dcaccf7b302a6268",
//                        "liked": false,
//                        "isPurchased": true,
//                        "isKYCApproved": false,
//                        "isBookMarked": false
//                      },{
//                          "_id": "652d31e9721c9436e3f3a66d",
//                          "postViewsCount": 64,
//                          "title": "",
//                          "imageUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/v1697460712/kozzii/posts/muq508zyorlaj9qpbznz.jpg",
//                          "thumbnailUrl1": "http://res.cloudinary.com/dozbw4cww/image/upload/t_media_lib_thumb/v1697460712/kozzii/posts/muq508zyorlaj9qpbznz.jpg",
//                          "mediaType1": 0,
//                          "userId": "65293e590ea7500199eac6a2",
//                          "createdOn": "2023-10-16T12:51:53.604",
//                          "timeStamp": 1697460713604,
//                          "distinctViews": 70,
//                          "totalViews": [],
//                          "imageUrl1Width": "720",
//                          "imageUrl1Height": "1080",
//                          "likesCount": 9,
//                          "mentionedUsers": [],
//                          "postStatus": 1,
//                          "shareCount": 0,
//                          "commentCount": 6,
//                          "cloudinary_public_id": "kozzii/posts/muq508zyorlaj9qpbznz",
//                          "userName": "harshareddy31",
//                          "firstName": "harsha",
//                          "lastName": "vardhan",
//                          "fullName": "harshavardhan",
//                          "fullNameWithSpace": "harsha vardhan",
//                          "profilepic": "",
//                          "profileCoverImage": "https://res.cloudinary.com/dx0qtfwvm/image/upload/t_media_lib_thumb/v1687417712/kozzii/cover_image/kozzii_xbjqr9.png",
//                          "categoryId": "",
//                          "categoryName": "",
//                          "categoryUrl": "",
//                          "musicId": "652d31e9721c940215f3a66e",
//                          "musicData": {},
//                          "location": {
//                            "longitude": 0,
//                            "latitude": 0
//                          },
//                          "place": "",
//                          "countrySname": "",
//                          "city": "",
//                          "placeId": "",
//                          "orientation": 0,
//                          "isStar": false,
//                          "trending_score": 0,
//                          "allowDownload": true,
//                          "allowComment": true,
//                          "allowDuet": true,
//                          "productIds": [],
//                          "productData": [],
//                          "cityForPost": "Shahmīrpet",
//                          "countryForPost": "IN",
//                          "latForPost": 17.4284406,
//                          "longForPost": 78.5840116,
//                          "locationForPost": {
//                            "lat": 17.4284406,
//                            "lon": 78.5840116
//                          },
//                          "isPrivate": 0,
//                          "isPaid": false,
//                          "postAmount": 0,
//                          "subscriptionAmount": 0,
//                          "TipsAmount": 0,
//                          "hashTags": [],
//                          "followStatus": 0,
//                          "postId": "652d31e9721c9436e3f3a66d",
//                          "liked": false,
//                          "isPurchased": true,
//                          "isKYCApproved": false,
//                          "isBookMarked": false
//                        }
//  ]
//}
//"""
//"http://res.cloudinary.com/dozbw4cww/video/upload/so_0/v1697460757/kozzii/posts/nyxq6o2qxaaxchhtn58s.jpg",
